hhru/balancing-http-client

- .gitignore
- setup.py
https://jira.hh.ru/browse/HH-121781
> HH-121781 Up tornado version upper bound

- http_client/__init__.py
https://jira.hh.ru/browse/HH-149661
> HH-149661 add __repr__ to RequestResult

- tests/test_balancing_base.py
https://jira.hh.ru/browse/HH-149874
> HH-149874 fix unstable tests

- http_client/__init__.py
нужна возможность управлять follow_redirects
> HH-150801 Add follow_redirects to put method

- http_client/__init__.py
ошибся в дефолте для put метода
> HH-150807 Add default idempotent=true to put handler

- http_client/options.py
- tests/test_balancing_base.py
- tests/test_parser.py
https://jira.hh.ru/browse/HH-157132
> HH-157132 remove tornado options

- http_client/__init__.py
https://jira.hh.ru/browse/HH-157513
> HH-157513 support different curl versions

- http_client/__init__.py
- tests/test_http_client_balancer.py
This reverts commit 0eacc0037137870beb67a76b33fbc1169b6387ad.
> Revert "HH-159276 add new debug logs"

- http_client/__init__.py
- http_client/balancing.py
- setup.py
- tests/test_balancing_in_application.py
- tests/test_balancing_tracing.py
- tests/test_upstream_profiles.py
https://jira.hh.ru/browse/HH-173265
> HH-173265 remove callbacks

- http_client/balancing.py
- setup.py
- tests/test_balancing_exceptionally_shutdown_server.py
- tests/test_balancing_gracefully_shutdown_server.py
- tests/test_balancing_low_backlog_server.py
- tests/test_balancing_resetting_server.py
- tests/test_http_client_parameters.py
https://jira.hh.ru/browse/HH-180269
> HH-180269 replace None headers with ''

- http_client/request_response.py
- pyproject.toml
- tests/test_balancing_tracing.py
https://jira.hh.ru/browse/HH-185303
> HH-185303 set 599 status in case of exception

- http_client/__init__.py
- http_client/balancing.py
- http_client/request_response.py
- pyproject.toml
https://jira.hh.ru/browse/HH-185497
> HH-185497 set error=None for status<400

- .hh-release.yaml
- http_client/__init__.py
- http_client/util.py
- http_client/version.py
- poetry.toml
- pyproject.toml
https://jira.hh.ru/browse/HH-189124
> HH-189124 small fixes

- .hh-release.yaml
- CODEOWNERS
- docker/Dockerfile.building
- http_client/version.py
- poetry.lock
- pyproject.toml
https://jira.hh.ru/browse/HH-189740
> HH-189740 add codeowners

- http_client/balancing.py
- http_client/options.py
- http_client/request_response.py
- http_client/util.py
- tests/test_adaptive_balancing_strategy.py
https://jira.hh.ru/browse/HH-204044
> HH-204044 cut unnecessary logs

- http_client/balancing.py
- http_client/options.py
- http_client/util.py
https://jira.hh.ru/browse/HH-205404
> HH-205404 use options for adaptive statistics logs

- http_client/balancing.py
- tests/test_balancing_base.py
https://jira.hh.ru/browse/HH-210380
> HH-210380 remove upstream manager

- http_client/balancing.py
- http_client/consul_parser.py
- http_client/request_response.py
- tests/test_adaptive_balancing_strategy.py
- tests/test_balancing_base.py
- tests/test_http_client_balancer.py
- tests/test_upstream_balancing.py
> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:
> HH-215261 add destination host

- README.md
- http_client/__init__.py
https://jira.hh.ru/browse/HH-216332
> HH-216332 small fixes

- http_client/__init__.py
- http_client/balancing.py
- http_client/options.py
- tests/test_balancing_tracing.py
- tests/test_upstream_profiles.py
https://jira.hh.ru/browse/HH-220770
> HH-220770 get adaptive flag from options

- http_client/balancing.py
- http_client/options.py
https://jira.hh.ru/browse/HH-225632
> HH-225632 rename setting

- http_client/__init__.py
- http_client/balancing.py
- http_client/testing.py
- tests/test_balancing_not_closed_socket_server.py
- tests/test_mock_http_client.py
https://jira.hh.ru/browse/HH-230620
> HH-230620 add mock_client

- http_client/__init__.py
https://jira.hh.ru/browse/HH-233061
> HH-233061 don't set request future result if request has canceled

- http_client/testing.py
https://jira.hh.ru/browse/HH-236220
> HH-236220 fix testing

- http_client/balancing.py
- http_client/options.py
> HH-237154 allow crossDc for specific upstreams
